kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: istio-demo-app
  namespace: fleet-default
spec:
  repo: https://github.com/atoy3731/istio-demo-app.git
  branch: main
  targets:
  - name: edge
    clusterSelector:
      matchLabels:
        type: edge
  paths:
  - ./k8s