apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: rancher-service-entry
  namespace: app1
spec:
  hosts:
  - www.rancher.com
  - rancher.com
  workloadSelector:
    labels:
      app: demo
  exportTo:
  - "."
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS