apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: controlplane
  namespace: istio-system
spec:
  components:
    ingressGateways:
    - enabled: true
      k8s:
        hpaSpec:
          maxReplicas: 1
          minReplicas: 1
        service:
          ports:
          - name: http
            port: 80
            protocol: TCP
            targetPort: 8080
          - name: https
            port: 443
            protocol: TCP
            targetPort: 8443
      name: istio-ingressgateway
    pilot:
      enabled: true
      k8s:
        hpaSpec:
          maxReplicas: 1
          minReplicas: 1
  meshConfig:
    outboundTrafficPolicy:
      mode: ALLOW_ANY
