apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: demo
        image: harbor.atoy.dev/public/istio-demo-app:1.0
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8080"
        - name: INTRA_URL
          value: http://demo.app1.svc.cluster.local:8080/status
        - name: CROSS_URL
          value: http://demo.app2.svc.cluster.local:8080/status
        - name: INTERNET_URL
          value: https://www.rancher.com
        # - name: AUTH_TOKEN
        #   value: "sup3r_s3cr3t"
        - name: DEBUG
          value: "true"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
